[tool.poetry]
name = "rahulbbot"
version = "0.1.0"
description = ""
authors = ["RahulB42 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pyTelegramBotAPI = "^3.7.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
